services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: xEGRk5H  # 必须设置的root密码
      MYSQL_ROOT_HOST: '%'  # 允许远程root访问
      MYSQL_DATABASE: test  # 可选：初始创建数据库
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql          # 数据持久化
      - ./mysql/conf.d:/etc/mysql/conf.d   # 自定义配置（可选）
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    external: false
