services:
  api:
    environment:
      - DASHBOARD_URL=https://10.1.24.26:3443/dashboard
      - DASHBOARD_BASE_API_URL=https://10.1.24.26:3443
      - PUBLIC_OIDC_DOMAIN=https://10.1.24.26:3443/dex
    volumes:
      - ./certs:/certs:ro

  proxy:
    environment:
      - OIDC_PUBLIC_DOMAIN=https://10.1.24.26:3443/dex

  dex:
    volumes:
      - ./dex/config.yaml:/etc/dex/config.yaml
      - ./certs:/certs:ro

  nginx:
    image: nginx:alpine
    ports:
      - "3443:3443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    networks:
      - daytona-network
    depends_on:
      - api
      - dex
    restart: always
