services:
  httpd:
    image: httpd:latest
    container_name: httpd
    hostname: httpd
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/:ro
